metadata:
- description: "\n            This ruleset gives hints to migrate kubernetes components
    to Quarkus extension\n        "
  dependencies:
    addon:
    - id: org.jboss.windup.rules,windup-rules-javaee,3.0.0.Final
    - id: org.jboss.windup.rules,windup-rules-java,3.0.0.Final
    - id: org.jboss.windup.rules,windup-rules-xml,3.0.0.Final
  sourceTechnology:
  - id: kubernetes
  targetTechnology:
  - id: quarkus
rules:
  rule:
  - when:
      project:
      - artifact:
          value: ""
          groupId: io.fabric8
          artifactId: kubernetes-client
    perform:
      iteration:
      - hint:
        - message: "\n                            Replace the `io.fabric8:kubernetes-client`
            dependency with the Quarkus dependency `io.quarkus:quarkus-kubernetes-client`
            \ \n                            Further information in the link below.\n
            \                       "
          link:
          - value: ""
            title: Quarkus - Guide
            href: https://quarkus.io/guides/kubernetes-client
          title: Replace the 'kubernetes-client' dependency with Quarkus 'quarkus-kubernetes-client'
            extension
          category-id: mandatory
          effort: 1
        over: default
  - when:
      dependency:
      - value: ""
        groupId: io.fabric8
        artifactId: kubernetes-client
    perform:
      hint:
      - message: "\n                        Replace the `io.fabric8:kubernetes-client`
          dependency with the Quarkus dependency `io.quarkus:quarkus-kubernetes-client`
          \ \n                        Further information in the link below.\n                    "
        link:
        - value: ""
          title: Quarkus - Guide
          href: https://quarkus.io/guides/kubernetes-client
        title: Replace the 'kubernetes-client' dependency with Quarkus 'quarkus-kubernetes-client'
          extension
        category-id: mandatory
        effort: 1
sourceFile: http://github.com/windup/windup-rulesets/tree/master/rules/rules-generated/quarkus/kubernetes/kubernetes-to-quarkus.windup.xml
