metadata:
- description: "\n            This ruleset provides analysis with respect to multiple
    Camel Context not supported in Apache Camel 3.\n        "
  dependencies:
    addon:
    - id: org.jboss.windup.rules,windup-rules-java,3.0.0.Final
  sourceTechnology:
  - id: camel
    versionRange: '[2,3)'
  targetTechnology:
  - id: camel
    versionRange: '[3,)'
rules:
  rule:
  - when:
      javaclass:
      - location:
        - ANNOTATION
        annotation-literal:
          name: context
          pattern: '{*}'
        references: org.apache.camel.{class}
    perform:
      hint:
      - message: "\n                        The `context` attribute on `{class}` annotations
          has been removed since support for multiple CamelContexts has been removed
          and only one CamelContext per deployment is supported.\n                    "
        link:
        - value: ""
          title: 'Camel 3 - Migration Guide: multiple CamelContexts per application
            not supported'
          href: https://camel.apache.org/manual/latest/camel-3-migration-guide.html#_multiple_camelcontexts_per_application_not_supported
        title: '{class}: `context` attribute removed'
        category-id: mandatory
        effort: 1
    where:
    - matches:
      - value: ""
        pattern: (BeanInject|Consume|DynamicRouter|EndpointInject|Produce|PropertyInject|RecipientList|RoutingSlip)
      param: class
  - when:
      javaclass:
      - location:
        - IMPORT
        references: org.apache.camel.cdi.{CdiCamelContextName}
    perform:
      hint:
      - message: "\n                        Support for multiple CamelContexts has
          been removed, and therefore `{CdiCamelContextName}` has been removed. Instead
          use standard CDI annotations such as `javax.inject.Named` and `javax.enterprise.context.ApplicationScoped`.\n
          \                   "
        link:
        - value: ""
          title: 'Camel 3 - Migration Guide: multiple CamelContexts per application
            not supported'
          href: https://camel.apache.org/manual/latest/camel-3-migration-guide.html#_camel_cdi
        title: '{CdiCamelContextName} has been removed'
        category-id: mandatory
        effort: 3
    where:
    - matches:
      - value: ""
        pattern: (ContextName|ContextNames)
      param: CdiCamelContextName
sourceFile: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/camel3/camel2/java-multiple-camelcontexts-per-application-not-supported.windup.xml
