metadata:
- description: "\n            Validate that all usages of System.getenv and System.getProperty
    are captured\n            as App Settings when migrating to Azure App Service.\n
    \       "
  dependencies:
    addon:
    - id: org.jboss.windup.rules,windup-rules-xml,3.0.0.Final
  sourceTechnology:
  - id: eap
    versionRange: '[7,8)'
  targetTechnology:
  - id: azure-appservice
  tag:
  - JBossEAP
  - Azure
rules:
  rule:
  - when:
      or:
      - javaclass:
        - location:
          - METHOD_CALL
          references: java.lang.System.getenv({*})
        - location:
          - METHOD_CALL
          references: java.lang.System.getProperty({*})
    perform:
      hint:
      - message: "\n                        \n                        App Service
          - The application reads environment variables.\n\n                        Any
          environment variables used in the code will need to be defined as App Settings,
          which are exposed\n                        as environment variables in App
          Service.\n\n                        Any System properties that the code
          depends on will need to be provided either in a custom Startup Script\n
          \                       or by defining an App Setting with the name JAVA_OPTS
          and include any system properties in it.\n                        \n                    "
        link:
        - value: ""
          title: Customization and tuning
          href: https://aka.ms/webapps-java-perf
        - value: ""
          title: Environment variables and app settings in Azure App Service
          href: https://aka.ms/webapps-env-vars
        title: App Service - The application reads environment variables
        category-id: optional
        effort: 1
sourceFile: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/azure/eap/eap-to-azure-appservice-environment-variables.windup.xml
