metadata:
- description: "\n            This ruleset provides analysis of Maven built applications
    that use JBoss EAP XP 2.x Bootable JAR Maven Plugin,\n            which configuration
    may need to be changed, when migrating to JBoss EAP XP 3.x or later.\n        "
  dependencies:
    addon:
    - id: org.jboss.windup.rules,windup-rules-javaee,3.0.0.Final
    - id: org.jboss.windup.rules,windup-rules-java,3.0.0.Final
    - id: org.jboss.windup.rules,windup-rules-xml,3.0.0.Final
  sourceTechnology:
  - id: eapxp
  targetTechnology:
  - id: eapxp
    versionRange: '[3,)'
  tag:
  - JBossEAP
  - EAPXP
rules:
  rule:
  - when:
      xmlfile:
      - namespace:
        - value: ""
          prefix: m
          uri: http://maven.apache.org/POM/4.0.0
        matches: //m:plugin[m:groupId/text() = 'org.wildfly.plugins' and m:artifactId/text()
          = 'wildfly-jar-maven-plugin']/m:configuration/m:extraServerContent
        in: pom.xml
    perform:
      hint:
      - message: If you migrate your application to JBoss EAP XP 3.0 (or later), and
          want to ensure its Maven building, running or testing works as expected,
          rename the configuration element `extraServerContent` to `extraServerContentDirs`.
        link:
        - value: ""
          title: 'JBoss EAP XP upgrade and migration guide: Bootable JAR application
            migration'
          href: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/jboss_eap_xp_upgrade_and_migration_guide/index#microprofile-application-migration-bootable-jar_default
        tag:
        - EAPXP
        title: 'Bootable JAR Maven Plugin: rename extraServerContent configuration
          element'
        category-id: potential
        effort: 1
sourceFile: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/eapxp/eapxp2/eapxp_bootable_jar_maven_plugin_configuration_changes.mta.xml
