metadata:
- description: "\n            This ruleset adds tags the configuration management
    technologies so are appropriately categorized on the technology reports.\n        "
  dependencies:
    addon:
    - id: org.jboss.windup.rules,windup-rules-javaee,3.0.0.Final
    - id: org.jboss.windup.rules,windup-rules-java,3.0.0.Final
  phase: PostMigrationRulesPhase
rules:
  rule:
  - when:
      graph-query:
      - property:
          name: name
        discriminator: TechnologyTagModel
    perform:
      technology-identified:
      - tag:
        - name: Sustain
        - name: Configuration Management
        - name: Embedded
        name: Spring Cloud Config
  - when:
      graph-query:
      - property:
          name: name
        discriminator: TechnologyTagModel
    perform:
      technology-identified:
      - tag:
        - name: Sustain
        - name: Configuration Management
        - name: Embedded
        name: Spring Properties
sourceFile: http://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed/technology-usage/configuration-management-technology-usage.windup.xml
